swc:
  name: "AppSWC"
  runnables:
    - name: "Init"
      initEvent: true
      reads:
        - port: "Rp_EcuVariant"
          dataElement: "Data"
    - name: "Cyclic_5ms"
      timingEventMs: 5
      calls:
        - port: "Rp_DiagHandling"
          operation: "SetEventStatus"
        - port: "Rp_DiagHandling"
          operation: "GetEventStatus"
    - name: "Runnable_MeasQueued"
      dataReceiveEvents:
        - port: Rp_MeasQueued
          dataElement: Value
    - name: Runnable_OnCommActive
      modeSwitchEvents:
        - port: Rp_CanCommState
          mode: BUS_ON
  ports:
    - name: "Rp_EcuVariant"
      direction: "requires"
      interfaceRef: If_EcuVariant
      comSpec:
        mode: explicit
    - name: "Rp_DiagHandling"
      direction: "requires"
      interfaceRef: "If_DiagHandling"
    - name: Rp_MeasQueued
      direction: requires
      interfaceRef: If_MeasurementsQueued
      comSpec:
        mode: queued
        queueLength: 5
    - name: Rp_CanCommState
      interfaceRef: If_CanCommState
      direction: requires